version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"  # Local port 3000 serves the React app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"